credentials:
  usernames:
    sshah:
      email:
      logged_in: False # Will be managed automatically
      name:
      password: password # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
